# Java Installation

[source,bash]
yum -y install java-1.8.0-openjdk-devel

# Install MariaDB
[source,bash]
sudo yum install mariadb-server
sudo systemctl stop mariadb

==== Update /etc/my.cnf

```
---

[mysqld]
datadir=/var/lib/mysql
socket=/var/lib/mysql/mysql.sock
transaction-isolation = READ-COMMITTED
# Disabling symbolic-links is recommended to prevent assorted security risks;
# to do so, uncomment this line:
symbolic-links = 0
# Settings user and group are ignored when systemd is used.
# If you need to run mysqld under a different user or group,
# customize your systemd unit file for mariadb according to the
# instructions in http://fedoraproject.org/wiki/Systemd

key_buffer = 16M
key_buffer_size = 32M
max_allowed_packet = 32M
thread_stack = 256K
thread_cache_size = 64
query_cache_limit = 8M
query_cache_size = 64M
query_cache_type = 1

max_connections = 550
#expire_logs_days = 10
#max_binlog_size = 100M

#log_bin should be on a disk with enough free space.
#Replace '/var/lib/mysql/mysql_binary_log' with an appropriate path for your
#system and chown the specified folder to the mysql user.
log_bin=/var/lib/mysql/mysql_binary_log

#In later versions of MariaDB, if you enable the binary log and do not set
#a server_id, MariaDB will not start. The server_id must be unique within
#the replicating group.
server_id=1

binlog_format = mixed

read_buffer_size = 2M
read_rnd_buffer_size = 16M
sort_buffer_size = 8M
join_buffer_size = 8M

# InnoDB settings
innodb_file_per_table = 1
innodb_flush_log_at_trx_commit  = 2
innodb_log_buffer_size = 64M
innodb_buffer_pool_size = 4G
innodb_thread_concurrency = 8
innodb_flush_method = O_DIRECT
innodb_log_file_size = 512M

[mysqld_safe]
log-error=/var/log/mariadb/mariadb.log
pid-file=/var/run/mariadb/mariadb.pid

#
# include all files from the config directory
#
!includedir /etc/my.cnf.d

---
```

==== Save and start MariaDB/MySQL
[source,bash]
sudo systemctl enable mariadb
sudo systemctl start mariadb

Run /usr/bin/mysql_secure_installation to set the MariaDB root password and other security-related settings. In a new installation, the root password is blank. 

[source,bash]
sudo /usr/bin/mysql_secure_installation


```
Enter current password for root (enter for none):
OK, successfully used password, moving on...
[...]
Set root password? [Y/n] Y
New password:
Re-enter new password:
[...]
Remove anonymous users? [Y/n] Y
[...]
Disallow root login remotely? [Y/n] N
[...]
Remove test database and access to it [Y/n] Y
[...]
Reload privilege tables now? [Y/n] Y
[...]
All done!  If you've completed all of the above steps, your MariaDB
installation should now be secure
Thanks for using MariaDB
```

=== Install Mysql/MariaDB connector
[source, bash]
wget https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.48.tar.gz
tar zxvf mysql-connector-java-5.1.48.tar.gz
sudo mkdir -p /usr/share/java/
cd mysql-connector-java-5.1.48
sudo cp mysql-connector-java-5.1.48-bin.jar /usr/share/java/mysql-connector-java.jar

=== Creation of needed users and databases
Login to mysql using root password and create databases
[source, bash]
mysql -u root -p

[source,sql]
CREATE DATABASE scm DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE DATABASE rman DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE DATABASE hue DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE DATABASE metastore DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE DATABASE sentry DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE DATABASE nav DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE DATABASE navms DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE DATABASE oozie DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
GRANT ALL ON scm.* TO 'scm'@'%' IDENTIFIED BY 'cloudera';
GRANT ALL ON rman.* TO 'rman'@'%' IDENTIFIED BY 'cloudera';
GRANT ALL ON sentry.* TO 'sentry'@'%' IDENTIFIED BY 'cloudera';
GRANT ALL ON hue.* TO 'hue'@'%' IDENTIFIED BY 'cloudera';
GRANT ALL ON oozie.* TO 'oozie'@'%' IDENTIFIED BY 'cloudera';
GRANT ALL ON navms.* TO 'navms'@'%' IDENTIFIED BY 'cloudera';
GRANT ALL ON nav.* TO 'nav'@'%' IDENTIFIED BY 'cloudera';
GRANT ALL ON metastore.* TO 'hive'@'%' IDENTIFIED BY 'cloudera';
CREATE DATABASE ranger DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
GRANT ALL ON ranger.* TO 'rangeradmin'@'%' IDENTIFIED BY 'cloudera';
SHOW DATABASES;

If GRANT is not working we can try below 
[source,bash]
CREATE USER 'scm'@'%' IDENTIFIED BY 'Cloudera@123';
GRANT ALL ON scm.* TO 'scm'@'%';
CREATE USER 'rman'@'%' IDENTIFIED BY 'Cloudera@123';
GRANT ALL ON rman.* TO 'rman'@'%';
CREATE USER 'sentry'@'%' IDENTIFIED BY 'Cloudera@123';
GRANT ALL ON sentry.* TO 'sentry'@'%';
CREATE USER 'hue'@'%' IDENTIFIED BY 'Cloudera@123';
GRANT ALL ON hue.* TO 'hue'@'%';
CREATE USER 'oozie'@'%' IDENTIFIED BY 'Cloudera@123';
GRANT ALL ON oozie.* TO 'oozie'@'%';
CREATE USER 'navms'@'%' IDENTIFIED BY 'Cloudera@123';
GRANT ALL ON navms.* TO 'navms'@'%';
CREATE USER 'nav'@'%' IDENTIFIED BY 'Cloudera@123';
GRANT ALL ON nav.* TO 'nav'@'%';
CREATE USER 'hive'@'%' IDENTIFIED BY 'Cloudera@123';
GRANT ALL ON metastore.* TO 'hive'@'%';
CREATE USER 'rangeradmin'@'%' IDENTIFIED BY 'Cloudera@123';
GRANT ALL ON ranger.* TO 'rangeradmin'@'%';


== Create local repository (If no internet access on the nodes)

[source,bash]
yum install -y httpd 
systemctl enable httpd 
systemctl start httpd 
mkdir -p /var/www/html/cloudera-repos/cm/7/7.5.4
mkdir -p /var/www/html/cloudera-repos/cdh/7/7.1.7 

== Download Packages
[source,bash]
https://<username:password>@archive.cloudera.com/p/cm5/repo-as-tarball/5.16.2/cm5.16.2-centos7.tar.gz
https://<username:password>@archive.cloudera.com/p/cdh5/parcels/5.16.2/CDH-5.16.2-1.cdh5.16.2.p0.8-el7.parcel
https://<username:password>@archive.cloudera.com/p/cdh5/parcels/5.16.2/CDH-5.16.2-1.cdh5.16.2.p0.8-el7.parcel.sha1
https://<username:password>@archive.cloudera.com/p/cdh5/parcels/5.16.2/manifest.json

[source,bash]
tar -xvzf cm5.16.2-centos7.tar.gz
mv cm/ /var/www/html/cloudera-repos/cm/5/5.16.2/


=== Create the CM Repo

[source,bash]
vi /etc/yum.repos.d/cloudera-manager.repo
[cloudera-manager]
name = Cloudera
baseurl = http://cloudnode1.purplepanda.ai/cloudera-repos/cm/5/5.16.2/cm/5.16.2/
gpgkey= http://cloudnode1.purplepanda.ai/cloudera-repos/cm/5/5.16.2/cm/RPM-GPG-KEY-cloudera
gpgcheck=1

=== Install packages

[source,bash]
yum -y install cloudera-manager-server
yum -y install cloudera-manager-agent cloudera-manager-daemons

=== Setup SCM database
[source,bash]
/usr/share/cmf/schema/scm_prepare_database.sh mysql scm scm cloudera

# Run CM server and agents

[source,bash]
systemctl start cloudera-scm-agent
systemctl enable cloudera-scm-agent
systemctl enable cloudera-scm-server
systemctl start cloudera-scm-server

=== Check it is started by looking at this line in file /var/log/cloudera-scm-server/cloudera-scm-server.log:

[source,bash]
sudo tail -f /var/log/cloudera-scm-server/cloudera-scm-server.log
> INFO WebServerImpl:com.cloudera.server.cmf.WebServerImpl: Started Jetty server.

