# sentry

Add Sentry Service

== Go to the hive => configuration 

- Sentry Service => select sentry
- Enable Stored Notifications in Database
- Disable HiveServer2 Enable Impersonation

== Go to the hue , Impala=> configuration 

- Sentry Service => select sentry

=== Restart Sentry, Hue, Hive, and Impala services
=== It should not be necessary to restart HDFS or YARN

# Verify user privileges

- Authenticate your user as a Kerberos principal 
- Use beeline to confirm your principal sees no tables
[source,bash]
beeline -u "jdbc:hive2://<hive2>:10000/default;principal=<hive_principal>@PURPLEPANDA.COM"
beeline -u "jdbc:hive2://cloudnode1.purplepanda.ai:10000/default;principal=hive/cloudnode1.purplepanda.ai@PURPLEPANDA.COM"

- Use your Linux account/password to authenticate when prompted
- Enter SHOW TABLES;
- The statement should return an empty set because no authorizations are in place
- Copy the transcript of this section to security/labs/sentry-test.md

# Create a Sentry role with full authorization
[source,bash]
In beeline:
CREATE ROLE sentry_admin;
GRANT ALL ON SERVER server1 TO ROLE sentry_admin;
GRANT ROLE sentry_admin TO GROUP {your_primary};
SHOW TABLES;
The statement should now return all tables


# Create additional test users
Add new users to all cluster nodes
[source,bash]
$ sudo groupadd selector
$ sudo groupadd inserters
$ sudo useradd -u 1100 -g selector george
$ sudo useradd -u 1200 -g inserters ferdinand
$ kadmin.local: add_principal george
$ kadmin.local: add_principal ferdinand

# Create test roles
Login to beeline as your admin user
[source,bash]
CREATE ROLE reads;
CREATE ROLE writes;
##Grant read privilege for all tables to reads
GRANT SELECT ON DATABASE default TO ROLE reads;
GRANT ROLE reads TO GROUP selector;
##Grant read privilege for default.sample07 only to 'writes':
REVOKE ALL ON DATABASE default FROM ROLE writes;
GRANT ALL ON default.sample_07 TO ROLE writes;
GRANT ROLE writes TO GROUP inserters;

IF sentry HDFS synchronisation is enable then give privileges to URI.
